### ISSUE TITLE
NoClassDef

### ISSUE THREAD

**Issue by Devinish** [cybertiger/Bukkit-Instances#45]
Got an error when loading Instances for the first time.

[12:42:22] [Server thread/ERROR]: Error occurred while enabling Instances v1.16-jetty (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/PacketType$Play$Client
	at org.cyberiantiger.minecraft.instances.unsafe.depend.ProtocolLibPacketHooksFactory.<clinit>(ProtocolLibPacketHooksFactory.java:79) ~[?:?]
	at org.cyberiantiger.minecraft.instances.Instances.onEnable(Instances.java:479) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:250) ~[craftbukkit_dev_3024.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324) [craftbukkit_dev_3024.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit_dev_3024.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
	at org.bukkit.craftbukkit.v1_7_R1.CraftServer.loadPlugin(CraftServer.java:439) [craftbukkit_dev_3024.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
	at org.bukkit.craftbukkit.v1_7_R1.CraftServer.enablePlugins(CraftServer.java:375) [craftbukkit_dev_3024.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.m(MinecraftServer.java:342) [craftbukkit_dev_3024.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.g(MinecraftServer.java:319) [craftbukkit_dev_3024.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.a(MinecraftServer.java:275) [craftbukkit_dev_3024.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
	at net.minecraft.server.v1_7_R1.DedicatedServer.init(DedicatedServer.java:175) [craftbukkit_dev_3024.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:424) [craftbukkit_dev_3024.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
	at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit_dev_3024.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.PacketType$Play$Client
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_51]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_51]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_51]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_51]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit_dev_3024.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit_dev_3024.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_51]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_51]
	... 13 more

Is ProtocolLib required or something?

**Comment by cybertiger** [comment]
ProtocolLib is not required, you may get some warnings like this if you don't have it though.
