### ISSUE TITLE
Ispawner wont work

### ISSUE THREAD

**Issue by TheRedPearl** [cybertiger/Bukkit-Instances#56]
I am using the Spigot / Craftbukkit  V.1.7.9 - 1.8 I am also using the latest Instances 1.16
Apon attempting to use the "/ispawner Zombie" i get the "An internal error occurred while attempting to perform this action."
The error code is shown below

------------------------------------------Code------------------------------------------
org.bukkit.command.CommandException: Unhandled exception executing command 'ispawner' in plugin Instances v1.16-jetty
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[craftbukkit.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[craftbukkit.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
Caused by: java.lang.NullPointerException
	at org.cyberiantiger.minecraft.instances.command.Spawner.execute(Spawner.java:155) ~[?:?]
	at org.cyberiantiger.minecraft.instances.command.AbstractCommand.execute(AbstractCommand.java:54) ~[?:?]
	at org.cyberiantiger.minecraft.instances.command.AbstractCommand.execute(AbstractCommand.java:44) ~[?:?]
	at org.cyberiantiger.minecraft.instances.Instances.onCommand(Instances.java:724) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-1.7.9-R0.2-204-g534549b]
	... 13 more
---------------------------------------------------------Code-----------------------------------------------

**Comment by cybertiger** [comment]
Fixed in latest release.
