### ISSUE TITLE
Error message on shutdown

### ISSUE THREAD

**Issue by OriginalMadman** [cybertiger/Bukkit-Instances#58]
This happens every time I shut the server

[18:05:57 ERROR]: Exception stopping the server
net.minecraft.server.v1_8_R1.ExceptionWorldConflict: Failed to check session lock for world located at plugins/Instances/worlds/2-16201345053238233016.world, aborting. Stop the server and delete the session.lock in this world to prevent further issues.
        at net.minecraft.server.v1_8_R1.WorldNBTStorage.checkSession(WorldNBTStorage.java:79) ~[spigot.jar:git-Spigot-47b1dff-f233e7d]
        at net.minecraft.server.v1_8_R1.World.checkSession(World.java:2785) ~[spigot.jar:git-Spigot-47b1dff-f233e7d]
        at net.minecraft.server.v1_8_R1.WorldServer.a(WorldServer.java:935) ~[spigot.jar:git-Spigot-47b1dff-f233e7d]
        at net.minecraft.server.v1_8_R1.WorldServer.save(WorldServer.java:907) ~[spigot.jar:git-Spigot-47b1dff-f233e7d]
        at net.minecraft.server.v1_8_R1.MinecraftServer.saveChunks(MinecraftServer.java:417) ~[spigot.jar:git-Spigot-47b1dff-f233e7d]
        at net.minecraft.server.v1_8_R1.MinecraftServer.stop(MinecraftServer.java:445) ~[spigot.jar:git-Spigot-47b1dff-f233e7d]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:561) [spigot.jar:git-Spigot-47b1dff-f233e7d]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]

**Comment by cybertiger** [comment]
Error is inconsequential since it's referring to instance worlds, which are deleted after a restart anyway.

It's still a strange error which shouldn't be happening, if I see something which could be causing it I will fix it. I use the same code in another one of my plugins InstantReset, and I haven't noticed this error.
