### ISSUE TITLE
Not working on Kcauldron (Error loading NBTTools)

### ISSUE THREAD

**Issue by Zarzuf** [cybertiger/Bukkit-Instances#66]
Hi,
I'm trying to use instances-1.16.jar on KCauldron-1.7.10-1517.168-server.jar, but it gives an error that prevents the mod from working. Here is the log:

[23:39:20 INFO]: [Instances] Enabling Instances v1.16-jetty
[23:39:20 INFO]: [Instances] Loading configuration
[23:39:20 INFO]: [Instances] Registering event handlers
[23:39:20 INFO]: [Instances] Creating NBTTools interface
[23:39:20 WARN]: [Instances] Error loading NBTTools.

java.lang.NullPointerException

at org.cyberiantiger.minecraft.unsafe.CBShim.createShim(CBShim.java:53) ~[instances-1.16.jar:?]

at org.cyberiantiger.minecraft.instances.Instances.onEnable(Instances.java:464) [instances-1.16.jar:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) [JavaPlugin.class:1.7.10-1517.168]

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1517.168]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1517.168]

at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:416) [CraftServer.class:1.7.10-1517.168]

at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:350) [CraftServer.class:1.7.10-1517.168]

at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:512) [MinecraftServer.class:?]

at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:486) [MinecraftServer.class:?]

at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:446) [MinecraftServer.class:?]

at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633) [MinecraftServer.class:?]

at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
[23:39:20 INFO]: [Instances] Creating InstanceTools interface
[23:39:20 WARN]: [Instances] Error loading InstanceTools.

java.lang.NullPointerException

at org.cyberiantiger.minecraft.unsafe.CBShim.createShim(CBShim.java:53) ~[instances-1.16.jar:?]

at org.cyberiantiger.minecraft.instances.Instances.onEnable(Instances.java:472) [instances-1.16.jar:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) [JavaPlugin.class:1.7.10-1517.168]

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1517.168]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1517.168]

at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:416) [CraftServer.class:1.7.10-1517.168]

at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:350) [CraftServer.class:1.7.10-1517.168]

at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:512) [MinecraftServer.class:?]

at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:486) [MinecraftServer.class:?]

at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:446) [MinecraftServer.class:?]

at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]

at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633) [MinecraftServer.class:?]

at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
[23:39:20 ERROR]: Error occurred while enabling Instances v1.16-jetty (Is it up to date?)

java.lang.NoClassDefFoundError: com/comphenix/protocol/PacketType$Play$Client

at org.cyberiantiger.minecraft.instances.unsafe.depend.ProtocolLibPacketHooksFactory.‹clinit›(ProtocolLibPacketHooksFactory.java:79) ~[?:?]

at org.cyberiantiger.minecraft.instances.Instances.onEnable(Instances.java:479) ~[?:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1517.168]

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1517.168]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1517.168]

at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:416) [CraftServer.class:1.7.10-1517.168]

at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:350) [CraftServer.class:1.7.10-1517.168]

at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:512) [MinecraftServer.class:?]

at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:486) [MinecraftServer.class:?]

at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:446) [MinecraftServer.class:?]

at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]

at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]

**Comment by cybertiger** [comment]
Does not work with KCauldron (or any spigot/forge hybrid) and is unlikely to start working without contributions from a developer than understands KCauldron.
