### ISSUE TITLE
KCauldron + 1.21

### ISSUE THREAD

**Issue by Jerry996666** [cybertiger/Bukkit-Instances#67]
What I get in my console.
`[22:34:34] [Server thread/WARN]: [Instances] bpaf is loaded, instances of loaded worlds may cause issues.
[22:34:34] [Server thread/WARN]: [Instances] Error creating instance
java.lang.IllegalArgumentException: Could not get provider type for dimension 36, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:178) ~[DimensionManager.class:1.7.10-1448.133]
	at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:472) ~[DimensionManager.class:1.7.10-1448.133]
	at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:160) ~[aqo.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:158) ~[mt.class:?]
	at org.cyberiantiger.minecraft.unsafe.v1_7_R4.InstanceTools.createInstance(InstanceTools.java:85) ~[instances-1.21.jar:?]
	at org.cyberiantiger.minecraft.instances.Instances.createInstance(Instances.java:394) [instances-1.21.jar:?]
	at org.cyberiantiger.minecraft.instances.InstanceEntrancePortal.onEnter(InstanceEntrancePortal.java:124) [instances-1.21.jar:?]
	at org.cyberiantiger.minecraft.instances.Instances.onPlayerMove(Instances.java:842) [instances-1.21.jar:?]
	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_79]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) [JavaPluginLoader$1.class:1.7.10-1448.133]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [RegisteredListener.class:1.7.10-1448.133]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1448.133]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1448.133]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:359) [nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) [jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(C03PacketPlayer.java:144) [je.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_79]
[22:34:34] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Instances v1.21-antony
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1448.133]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1448.133]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1448.133]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1448.133]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:359) [nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) [jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(C03PacketPlayer.java:144) [je.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_79]
Caused by: java.lang.NullPointerException
	at org.cyberiantiger.minecraft.Cuboid.isEmpty(Cuboid.java:109) ~[?:?]
	at org.cyberiantiger.minecraft.Cuboid.getCenterFloor(Cuboid.java:120) ~[?:?]
	at org.cyberiantiger.minecraft.instances.Portal.teleport(Portal.java:37) ~[?:?]
	at org.cyberiantiger.minecraft.instances.InstanceEntrancePortal.onEnter(InstanceEntrancePortal.java:158) ~[?:?]
	at org.cyberiantiger.minecraft.instances.Instances.onPlayerMove(Instances.java:842) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_79]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1448.133]
	... 13 more`

**Comment by cybertiger** [comment]
Does not work with KCauldron, and without some help from someone who understands KCauldron, it's not likely to ever work.
