### ISSUE TITLE
Spigot 1.9.4

### ISSUE THREAD

**Issue by RogerPlaysMC** [cybertiger/Bukkit-Instances#73]
Is there anyway you could update for 1.9.4?
`[15:47:43 WARN]: [Instances] Error creating instance
java.lang.IllegalStateException: Unsupported server version: 1.9.4-R0.1-SNAPSHOT
        at org.cyberiantiger.minecraft.instances.Instances.createInstance(Instances.java:378) [instances-1.22.jar:?]
        at org.cyberiantiger.minecraft.instances.InstanceEntrancePortal.onEnter(InstanceEntrancePortal.java:124) [instances-1.22.jar:?]
        at org.cyberiantiger.minecraft.instances.Instances.onPlayerMove(Instances.java:842) [instances-1.22.jar:?]
        at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:607) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.PacketPlayInFlying.a(SourceFile:126) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[15:47:43 ERROR]: Could not pass event PlayerMoveEvent to Instances v1.22-antony
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:607) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.PacketPlayInFlying.a(SourceFile:126) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at org.cyberiantiger.minecraft.Cuboid.isEmpty(Cuboid.java:109) ~[?:?]
        at org.cyberiantiger.minecraft.Cuboid.getCenterFloor(Cuboid.java:120) ~[?:?]
        at org.cyberiantiger.minecraft.instances.Portal.teleport(Portal.java:37) ~[?:?]
        at org.cyberiantiger.minecraft.instances.InstanceEntrancePortal.onEnter(InstanceEntrancePortal.java:158) ~[?:?]
        at org.cyberiantiger.minecraft.instances.Instances.onPlayerMove(Instances.java:842) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
        ... 15 more`

**Comment by cybertiger** [comment]
Updated
