### ISSUE TITLE
Internal error occured when attempting to do /isetentrance or /isetdestination

### ISSUE THREAD

**Issue by CutieCake2k** [cybertiger/Bukkit-Instances#77]
Also, when someone makes a party and goes into an existing portal, it goes nowhere. I am lost here. All my plugins are updated, so I don't know what the issue could be. (Also, I keep getting spam in the console with similar errors to when I try to make a portal). This is the log from the console. These errors appear when I attempt to do the commands in the title, or when players are doing random things (not related to the instance world).

MinecraftServer.run(MinecraftServer.java:572) [spigot.jar:git-Spigot-9797151-301db84]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
Caused by: java.lang.NullPointerException
    at org.cyberiantiger.minecraft.instances.Instances.onClick(Instances.java:888) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor188.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-9797151-301db84]
    ... 18 more
[13:17:09] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Instances v1.24-antony
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-9797151-301db84]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-9797151-301db84]
    at me.Incomprehendable.WorldPlugins.FakePluginManager.fireEvent(FakePluginManager.java:138) [PerWorldPlugins.jar:?]
    at me.Incomprehendable.WorldPlugins.FakePluginManager.callEvent(FakePluginManager.java:124) [PerWorldPlugins.jar:?]
    at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:492) [spigot.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:890) [spigot.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-9797151-301db84]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_77]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_77]
    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737) [spigot.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot.jar:git-Spigot-9797151-301db84]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
Caused by: java.lang.NullPointerException
    at org.cyberiantiger.minecraft.instances.Instances.onClick(Instances.java:888) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor188.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-9797151-301db84]
    ... 17 more
[13:17:09] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Instances v1.24-antony
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-9797151-301db84]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-9797151-301db84]
    at me.Incomprehendable.WorldPlugins.FakePluginManager.fireEvent(FakePluginManager.java:138) [PerWorldPlugins.jar:?]
    at me.Incomprehendable.WorldPlugins.FakePluginManager.callEvent(FakePluginManager.java:124) [PerWorldPlugins.jar:?]
    at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot.jar:git-Spigot-9797151-301db84]
    at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) [spigot.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:111) [spigot.jar:git-Spigot-9797151-301db84]
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:834) [s

**Comment by Scratch741** [comment]
My instances works fine bud it throws tons of errors after entering a portal.

**Comment by Scratch741** [comment]
Use 1.9.2 Spigot
